# Generated by Django 5.0.7 on 2024-07-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('course', models.CharField(max_length=100)),
                ('course_level', models.CharField(blank=True, max_length=2, null=True)),
                ('teacher', models.CharField(blank=True, max_length=20, null=True)),
                ('classroom', models.CharField(max_length=50)),
                ('day_of_week', models.CharField(max_length=2)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
